### ISSUE TITLE
Kakashi Hatake

### ISSUE THREAD

**Issue by Hanzo253** [law-millenium/naruto-progress#2]
Hello Law Millenium,

This is not an issue, but I wanted to ask if there was a working version with a Kakashi icon included? I been enjoying this awesome plugin, but wanted Kakashi included.

Thank you!

**Comment by law-millenium** [comment]
Hello Hanzo,

I didn't have a lot of time recently to work on this plugin but I'm about to have some time to do so !
And, about Kakashi, he's already in a feature branch that i'll release soon !! 😄
Hope you'll enjoy this plugin even more this way (you'll see a surprise 😉), don't hesitate to ask again if you want specific content (it can be done quickly if you have pixel-art gifs already made or sprites corresponding to what you'd like).

See u !

**Comment by Hanzo253** [comment]
Ah I see, no worries. Thank you for the response, very much appreciated. Glad to hear it and looking forward to it!

**Comment by law-millenium** [comment]
Hey!
I released a new version and it's been approved by Jetbrains, you can update it in order to find Kakashi and Kakashi with Anbu outfit!
Hope you'll enjoy this!
